"""
The central ERDDAP: datasets.xml generation and per-dataset reloads.

datasets.xml is a build artefact. It is written from the datasets the database
says are healthy, so hand-editing it is always wrong - the next run overwrites
it. Two safeguards, both learned the hard way:

  * The generated XML is parsed before it replaces the live file. A malformed
    datasets.xml makes ERDDAP silently keep the previous one, so the federation
    looks fine while being hours stale.
  * Every build keeps a timestamped backup, so rolling back is a copy rather
    than a re-run of the whole gate.
"""

from __future__ import annotations

import datetime as dt
import logging
import os
import shutil
import xml.etree.ElementTree as ET
from xml.sax.saxutils import escape

logger = logging.getLogger("gate")

HEADER_FILE = "datasets_header.xml"
FOOTER_FILE = "datasets_footer.xml"


class ErddapError(Exception):
    """The generated datasets.xml is not usable and must not be deployed."""


class ErddapHelper:
    """Writes datasets.xml and asks ERDDAP to reload what changed."""

    def __init__(self, cfg) -> None:
        self.cfg = cfg
        self.target = cfg.path("datasets_xml")
        self.templates_dir = cfg.path("templates_dir")
        self.data_dir = cfg.path("erddap_data_dir")

    # ------------------------------------------------------------------
    def build_datasets(self, datasets: list) -> str:
        """
        Rewrite datasets.xml from *datasets* and return the path written.

        *datasets* are the database rows of everything currently healthy -
        mappings with dataset_id, source_url, erddap_type and default_query.
        """
        header = self._template(HEADER_FILE)
        footer = self._template(FOOTER_FILE)

        blocks = [
            self._dataset_block(
                dataset_id=row["dataset_id"],
                source_url=row["source_url"],
                erddap_type=row.get("erddap_type") or "EDDTableFromErddap",
                default_query=row.get("default_query") or "",
            )
            for row in datasets
        ]

        stamp = dt.datetime.now(dt.timezone.utc).strftime("%Y-%m-%d %H:%M:%SZ")
        # The templates carry these placeholders in their ERDDAP-facing text.
        header = (header.replace("__DATASETS_XML_BUILD_DATE__", stamp)
                        .replace("__DATASETS_XML_COUNT__", str(len(blocks))))

        banner = "\n".join([
            "<!-- =================================================================== -->",
            "<!-- GENERATED BY THE EMSO VALIDATION GATE - DO NOT EDIT BY HAND.        -->",
            "<!-- The next run overwrites this file. Edit federation/ instead.        -->",
            f"<!-- generated : {stamp:<55s}-->",
            f"<!-- datasets  : {len(blocks):<55d}-->",
            "<!-- =================================================================== -->",
        ])

        content = "\n".join([
            header.rstrip(), "", banner, "",
            "\n\n".join(blocks), "",
            footer.lstrip(),
        ]) + "\n"

        return self._write(content)

    def existing_dataset_ids(self) -> set[str]:
        """
        datasetIDs already in the live file, to work out what to reload.

        A missing or malformed file yields an empty set, which makes the next
        run flag everything: noisy, but better than deploying against a wrong
        picture of the current state.
        """
        if not os.path.isfile(self.target):
            return set()
        try:
            tree = ET.parse(self.target)
        except ET.ParseError as exc:
            logger.warning("could not parse the existing %s: %s", self.target, exc)
            return set()
        return {
            element.attrib["datasetID"]
            for element in tree.getroot().iter("dataset")
            if "datasetID" in element.attrib
        }

    def reload_dataset(self, dataset_id: str) -> bool:
        """
        Ask ERDDAP to reload one dataset by touching its flag file.

        Reloading one dataset leaves the rest of the federation serving;
        restarting ERDDAP or waiting for loadDatasetsMinMinutes does not.

        hardflag also discards ERDDAP's cached shape information. That is the
        default because every dataset here is an EDD*FromErddap proxy: what
        gets cached is the *regional* dataset's variable list, so when a
        facility adds a variable a soft flag reloads the dataset while keeping
        the stale structure - a dataset that looks reloaded and serves the old
        shape.
        """
        if self.cfg.reload_method == "none":
            return False
        subdirectory = "hardFlag" if self.cfg.reload_method == "hardflag" else "flag"
        directory = os.path.join(self.data_dir, subdirectory)
        try:
            os.makedirs(directory, exist_ok=True)
            with open(os.path.join(directory, dataset_id), "w", encoding="utf-8"):
                pass
        except OSError as exc:
            logger.warning("could not flag %s for reload: %s", dataset_id, exc)
            return False
        return True

    # ------------------------------------------------------------------
    @staticmethod
    def _dataset_block(dataset_id: str, source_url: str, erddap_type: str,
                       default_query: str, reload_minutes: int = 60) -> str:
        """
        One <dataset> element, as ERDDAP's *FromErddap types expect it.

        These are thin proxies: the central node holds no data and re-serves
        the regional dataset, which is what makes the federation a view over
        the facilities rather than a copy of them.
        """
        lines = [
            f'<dataset type="{escape(erddap_type)}" '
            f'datasetID="{escape(dataset_id)}" active="true">',
            f"    <sourceUrl>{escape(source_url)}</sourceUrl>",
            f"    <reloadEveryNMinutes>{int(reload_minutes)}</reloadEveryNMinutes>",
        ]
        if default_query:
            # Already percent-encoded in the registry; escape only the XML
            # metacharacters so an ampersand cannot end the element early.
            lines.append(
                f"    <defaultGraphQuery>{escape(default_query)}</defaultGraphQuery>"
            )
        lines.append("</dataset>")
        return "\n".join(lines)

    def _template(self, name: str) -> str:
        path = os.path.join(self.templates_dir, name)
        if not os.path.isfile(path):
            raise ErddapError(
                f"missing datasets.xml template {path}; the gate will not "
                f"invent an ERDDAP configuration"
            )
        with open(path, encoding="ISO-8859-1") as f:
            return f.read()

    def _write(self, content: str) -> str:
        try:
            ET.fromstring(content)
        except ET.ParseError as exc:
            raise ErddapError(
                f"the generated datasets.xml does not parse ({exc}); the live "
                f"file has been left untouched"
            ) from exc

        os.makedirs(os.path.dirname(os.path.abspath(self.target)) or ".",
                    exist_ok=True)

        if os.path.isfile(self.target):
            backup_dir = f"{self.target}.backups"
            os.makedirs(backup_dir, exist_ok=True)
            stamp = dt.datetime.now(dt.timezone.utc).strftime("%Y%m%dT%H%M%SZ")
            shutil.copy2(self.target,
                         os.path.join(backup_dir, f"datasets.{stamp}.xml"))
            self._prune_backups(backup_dir)

        # Written in place rather than via os.replace: datasets.xml is a
        # bind-mounted file in the ERDDAP container, and replacing the inode
        # would leave the container holding the old one.
        with open(self.target, "w", encoding="ISO-8859-1",
                  errors="xmlcharrefreplace") as f:
            f.write(content)
        logger.info("wrote %s", self.target)
        return self.target

    def _prune_backups(self, directory: str) -> None:
        backups = sorted(
            name for name in os.listdir(directory)
            if name.startswith("datasets.") and name.endswith(".xml")
        )
        keep = max(1, self.cfg.keep_backups)
        for name in backups[: max(0, len(backups) - keep)]:
            try:
                os.remove(os.path.join(directory, name))
            except OSError as exc:
                logger.debug("could not prune backup %s: %s", name, exc)
